[package]
name = "taylor"
version = "0.1.0"
edition.workspace = true

[dependencies]
symm = { workspace = true }
nalgebra = { workspace = true }
anpass = { workspace = true }
serde = { workspace = true }