
.RE
.fi

.SH PROGRAM-SPECIFIC DETAILS
The following sections contain program-specific details about the config file.
.SS DFTB+
Thanks to DFTB+'s strange input format,
.BR pbqff
has a relatively harder time automatically removing geometry optimization
directives from the input template. As such, it expects a template like the one
shown below:

.nf
.rs
Driver = GeometryOptimization {
  Optimizer = Rational {}
  MovedAtoms = 1:-1
  MaxSteps = 100
  OutputPrefix = "geom.out"
  Convergence {
    Energy = 1e-8
    GradElem = 1e-8
    GradNorm = 1e-7
    DispElem = 1e-7
    DispNorm = 1e-7
  }
}
.RE
.fi

In particular,
.BR pbqff
will only recognize the exact pattern
.BR Driver
.BR =
.BR GeometryOptimization
for identifying optimization input (though it ignores case). For single-point
energy calculations, it will strip this out, and for geometry optimizations, it
will refrain from adding the default optimization commands.

.nf
.rs

