#!/bin/bash

brent=/ddn/home1/r2518
host=$(hostname)
case $host in
    sequoia)
	module load python/3.7
	;;
    maple)
	module load python37
	;;
esac
python3.7 $brent/bin/qffbuddy.py --pbqff $brent/bin/rpbqff "$@"
