[package]
name = "rust-pbqff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.30.1"
psqs = { path = "/home/brent/Projects/psqs" }
taylor = { path = "/home/brent/Projects/taylor" }
intder = { path = "/home/brent/Projects/intder" }
spectro = { path = "/home/brent/Projects/spectro" }
rust-anpass = { path = "/home/brent/Projects/rust-anpass" }
summarize = { path = "/home/brent/Projects/summarize" }
symm = { path = "/home/brent/Projects/symm" }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2.126"

[dev-dependencies]
approx = "0.5.1"
