[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
psqs = { path = "crates/psqs" }
symm = { path = "crates/symm" }
intder = { path = "crates/intder" }
spectro = { path = "crates/spectro" }

tensor = { git = "https://github.com/ntBre/tensor" }
rust-anpass = { git = "https://github.com/ntBre/rust-anpass" }
taylor = { git = "https://github.com/ntBre/taylor" }

approx = "0.5.1"
assert_cmd = "2.0.16"
chrono = "0.4.23"
clap = { version = "4.5.23", features = ["derive"] }
criterion = "0.5.0"
env_logger = "0.11.3"
insta = { version = "1.41.1", features = ["filters"] }
libc = "0.2.169"
log = "0.4.22"
nalgebra = "0.33.2"
ndarray = { version = "0.15.6", features = ["approx-0_5"] }
rayon = "1.5.3"
regex = { version = "1.9.1" }
rustc-hash = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.14.0"
test-case = "3.3.1"
toml = "0.8.10"
