[package]
name = "rust-pbqff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intder = { git = "https://github.com/ntBre/intder" }
libc = "0.2.150"
nalgebra = "0.32.3"
psqs = { git = "https://github.com/ntBre/psqs" }
rust-anpass = { git = "https://github.com/ntBre/rust-anpass" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
spectro = { git = "https://github.com/ntBre/spectro" }
symm = { git = "https://github.com/ntBre/symm" }
taylor = { git = "https://github.com/ntBre/taylor" }
toml = "0.8.8"
rustc-hash = "1.1.0"
clap = { version = "4.4.7", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
tempfile = "3.8.1"

[[bin]]
name = "cart"
path = "src/bin/cart.rs"

[build-dependencies]
git2 = { version = "0.18.0", optional = true }

[features]
vers = ["dep:git2"]
