[package]
name = "rust-pbqff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psqs = { path = "/home/brent/Projects/psqs" }
intder = { path = "/home/brent/Projects/intder" }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }