[package]
name = "rust-pbqff"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"dispatch",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intder = { path = "/home/brent/Projects/intder" }
libc = "0.2.126"
nalgebra = "0.32.2"
psqs = { path = "/home/brent/Projects/psqs" }
rust-anpass = { git = "https://github.com/ntBre/rust-anpass" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
spectro = { path = "/home/brent/Projects/spectro/spectro" }
symm = { git = "https://github.com/ntBre/symm" }
taylor = { path = "/home/brent/Projects/taylor" }
toml = "0.5.8"
rustc-hash = "1.1.0"
clap = { version = "4.0.18", features = ["derive"] }
dispatch = { path = "dispatch" }

[dev-dependencies]
approx = "0.5.1"

[[bin]]
name = "cart"
path = "src/bin/cart.rs"

[build-dependencies]
git2 = "0.15.0"
