[package]
name = "rust-pbqff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intder = { path = "/home/brent/Projects/intder" }
libc = "0.2.126"
nalgebra = "0.31.1"
psqs = { path = "/home/brent/Projects/psqs" }
rust-anpass = { path = "/home/brent/Projects/rust-anpass" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
spectro = { path = "/home/brent/Projects/spectro/spectro" }
symm = { path = "/home/brent/Projects/symm" }
taylor = { path = "/home/brent/Projects/taylor" }
toml = "0.5.8"
rustc-hash = "1.1.0"
regex = "1.5.5"

[dev-dependencies]
approx = "0.5.1"

[[bin]]
name = "cart"
path = "src/bin/cart.rs"