queue_template = """
#!/bin/sh
#PBS -N {{{{.basename}}}}
#PBS -S /bin/bash
#PBS -j oe
#PBS -o {{{{.filename}}}}.out
#PBS -W umask=022
#PBS -l walltime=1000:00:00
#PBS -l ncpus=1
#PBS -l mem=8gb
#PBS -q workq

module load openpbs

export WORKDIR=$PBS_O_WORKDIR
cd $WORKDIR

export DFTB_CMD=/ddnlus/r2518/.conda/envs/dftb/bin/dftb+
"""