[package]
name = "spectro_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
spectro = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

[features]
polyad = ["spectro/polyad"]