permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

name: test
jobs:
  required:
    runs-on: ubuntu-latest
    env:
        PSQS_NO_RESUB: 1
    name: ubuntu
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile

      - name: install mopac
        run: |
            set -xe
            curl -OL https://github.com/openmopac/mopac/releases/download/v23.0.2/mopac-23.0.2-linux.tar.gz
            gunzip mopac-23.0.2-linux.tar.gz
            tar xf mopac-23.0.2-linux.tar
            mkdir -p /opt/mopac
            cp mopac-23.0.2-linux/bin/mopac /opt/mopac/.
            cp mopac-23.0.2-linux/lib/*.so* /opt/mopac/.
            ls /opt/mopac
            ldd /opt/mopac/mopac

      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets -- --include-ignored --nocapture
